<script lang="ts">
  import type { PageData } from './$types';
  import { CheckCircle, Shield, XCircle } from '@lucide/svelte';

  let { data }: { data: PageData } = $props();
  const v = data.verified;

  function formatDate(iso: string | null) {
    if (!iso) return 'N/A';
    return new Date(iso).toLocaleDateString('en-NG', { day:'numeric', month:'long', year:'numeric' });
  }
</script>

<svelte:head><title>Verify Result — MOUAU eTest</title></svelte:head>

<div class="verify-page">
  <div class="verify-card">
    <div class="verify-header">
      <Shield size={40} color="#10b981"/>
      <h1>Result Verification</h1>
      <p>Michael Okpara University of Agriculture, Umudike — eTest Platform</p>
    </div>

    <div class="verify-status" class:pass={v.passed} class:fail={!v.passed}>
      {#if v.passed}
        <CheckCircle size={20}/> Verified — Passed
      {:else}
        <XCircle size={20}/> Verified — Not Passed
      {/if}
    </div>

    <div class="verify-grid">
      <div class="vrow"><span>Student Name</span><strong>{v.studentName}</strong></div>
      <div class="vrow"><span>Matric Number</span><strong>{v.matricNumber}</strong></div>
      <div class="vrow"><span>Department</span><strong>{v.department}</strong></div>
      <div class="vrow"><span>Course</span><strong>{v.courseCode} — {v.courseTitle}</strong></div>
      <div class="vrow"><span>Exam</span><strong>{v.examTitle}</strong></div>
      <div class="vrow"><span>Score</span><strong>{v.score != null ? `${v.score}%` : 'N/A'}</strong></div>
      <div class="vrow"><span>Grade</span><strong>{v.grade ?? 'N/A'}</strong></div>
      <div class="vrow"><span>Session</span><strong>{v.session} — Semester {v.semester}</strong></div>
      <div class="vrow"><span>Submitted</span><strong>{formatDate(v.submittedAt)}</strong></div>
      <div class="vrow"><span>Record Issued</span><strong>{formatDate(v.issuedAt)}</strong></div>
    </div>

    <div class="verify-disclaimer">
      <Shield size={12}/>
      This record is generated by the MOUAU eTest platform and is <strong>not an official transcript or certificate endorsed by Michael Okpara University of Agriculture, Umudike</strong>.
    </div>
  </div>
</div>

<style>
  .verify-page { min-height: 100vh; display: flex; align-items: center; justify-content: center; background: var(--color-bg, #f9fafb); padding: 2rem; }
  .verify-card { width: 100%; max-width: 560px; background: white; border: 1px solid #e5e7eb; border-radius: 1.25rem; overflow: hidden; box-shadow: 0 8px 32px rgba(0,0,0,.08); }
  .verify-header { display: flex; flex-direction: column; align-items: center; gap: .5rem; padding: 2rem; border-bottom: 1px solid #e5e7eb; text-align: center; }
  .verify-header h1 { font-size: 1.35rem; font-weight: 900; color: #111827; margin: 0; }
  .verify-header p { font-size: .8rem; color: #6b7280; margin: 0; }
  .verify-status { display: flex; align-items: center; justify-content: center; gap: .5rem; padding: .875rem; font-weight: 700; font-size: .9rem; }
  .verify-status.pass { background: color-mix(in srgb,#10b981 10%,white); color: #065f46; border-bottom: 1px solid color-mix(in srgb,#10b981 20%,transparent); }
  .verify-status.fail { background: color-mix(in srgb,#ef4444 10%,white); color: #991b1b; border-bottom: 1px solid color-mix(in srgb,#ef4444 20%,transparent); }
  .verify-grid { display: flex; flex-direction: column; padding: 1.25rem 1.5rem; gap: .5rem; }
  .vrow { display: flex; justify-content: space-between; align-items: center; padding: .5rem 0; border-bottom: 1px solid #f3f4f6; font-size: .875rem; gap: 1rem; }
  .vrow span { color: #6b7280; flex-shrink: 0; }
  .vrow strong { color: #111827; text-align: right; }
  .verify-disclaimer { display: flex; align-items: flex-start; gap: .5rem; padding: 1rem 1.5rem; background: #fef3c7; font-size: .72rem; color: #92400e; line-height: 1.55; }
</style>