<!-- src/routes/s/verify/[resultId]/+page.svelte -->
<script lang="ts">
  import type { PageData } from './$types';
  import { CheckCircle, Shield, XCircle, Download } from '@lucide/svelte';
  import { onMount } from 'svelte';
  import { page } from '$app/stores';

  let { data }: { data: PageData } = $props();
  const v = data.verified;

  // ── QR code ───────────────────────────────────────────────────────────────
  let canvasEl = $state<HTMLCanvasElement | null>(null);
  let qrUrl = $state('');
  let isQrReady = $state(false);

  onMount(async () => {
    // Build the full public verification URL from the current page URL
    qrUrl = $page.url.href;

    try {
      // qrcode is a zero-dependency CJS/ESM package — import dynamically so
      // the page still renders even if the package is missing.
      const QRCode = (await import('qrcode')).default;
      if (canvasEl) {
        await QRCode.toCanvas(canvasEl, qrUrl, {
          width: 160,
          margin: 2,
          color: { dark: '#111827', light: '#ffffff' },
        });
        isQrReady = true;
      }
    } catch (e) {
      console.warn('QR code generation failed:', e);
    }
  });

  function downloadQR() {
    if (!canvasEl) {
      console.warn('Canvas element not ready');
      return;
    }
    try {
      const link = document.createElement('a');
      link.download = `result-${v.matricNumber || 'verification'}.png`;
      link.href = canvasEl.toDataURL('image/png');
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (e) {
      console.error('Failed to download QR code:', e);
    }
  }

  function formatDate(iso: string | null) {
    if (!iso) return 'N/A';
    return new Date(iso).toLocaleDateString('en-NG', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });
  }
</script>

<svelte:head>
  <title>Verify Result — MOUAU eTest</title>
</svelte:head>

<div class="verify-page">
  <div class="verify-card">
    <div class="verify-header">
      <Shield size={40} color="#10b981" />
      <h1>Result Verification</h1>
      <p>Michael Okpara University of Agriculture, Umudike — eTest Platform</p>
    </div>

    <div class="verify-status" class:pass={v.passed} class:fail={!v.passed}>
      {#if v.passed}
        <CheckCircle size={20} /> Verified — Passed
      {:else}
        <XCircle size={20} /> Verified — Not Passed
      {/if}
    </div>

    <div class="verify-body">
      <!-- Result rows -->
      <div class="verify-grid">
        <div class="vrow"><span>Student Name</span><strong>{v.studentName}</strong></div>
        <div class="vrow"><span>Matric Number</span><strong>{v.matricNumber}</strong></div>
        <div class="vrow"><span>Department</span><strong>{v.department}</strong></div>
        <div class="vrow"><span>Course</span><strong>{v.courseCode} — {v.courseTitle}</strong></div>
        <div class="vrow"><span>Exam</span><strong>{v.examTitle}</strong></div>
        <div class="vrow"><span>Score</span><strong>{v.score != null ? `${v.score}%` : 'N/A'}</strong></div>
        <div class="vrow"><span>Grade</span><strong>{v.grade ?? 'N/A'}</strong></div>
        <div class="vrow"><span>Session</span><strong>{v.session} — Semester {v.semester}</strong></div>
        <div class="vrow"><span>Submitted</span><strong>{formatDate(v.submittedAt)}</strong></div>
        <div class="vrow"><span>Record Issued</span><strong>{formatDate(v.issuedAt)}</strong></div>
      </div>

      <!-- QR code panel -->
      <div class="qr-panel">
        <div class="qr-wrap">
          <canvas bind:this={canvasEl} class="qr-canvas"></canvas>
        </div>
        <p class="qr-label">Scan to verify</p>
        <button 
          class="qr-download" 
          onclick={downloadQR} 
          type="button"
          disabled={!isQrReady}
        >
          <Download size={12} /> Save QR
        </button>
      </div>
    </div>

    <div class="verify-disclaimer">
      <Shield size={12} />
      This record is generated by the MOUAU eTest platform and is
      <strong>not an official transcript or certificate endorsed by
      Michael Okpara University of Agriculture, Umudike</strong>.
    </div>
  </div>
</div>

<style>
  .verify-page {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--color-bg, #f9fafb);
    padding: 2rem 1rem;
  }

  .verify-card {
    width: 100%;
    max-width: 640px;
    background: white;
    border: 1px solid #e5e7eb;
    border-radius: 1.25rem;
    overflow: hidden;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.08);
  }

  /* ── Header ──────────────────────────────────────────────────────────── */
  .verify-header {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    padding: 2rem;
    border-bottom: 1px solid #e5e7eb;
    text-align: center;
  }
  .verify-header h1 {
    font-size: 1.35rem;
    font-weight: 900;
    color: #111827;
    margin: 0;
  }
  .verify-header p {
    font-size: 0.8rem;
    color: #6b7280;
    margin: 0;
  }

  /* ── Status bar ──────────────────────────────────────────────────────── */
  .verify-status {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: 0.875rem;
    font-weight: 700;
    font-size: 0.9rem;
  }
  .verify-status.pass {
    background: color-mix(in srgb, #10b981 10%, white);
    color: #065f46;
    border-bottom: 1px solid color-mix(in srgb, #10b981 20%, transparent);
  }
  .verify-status.fail {
    background: color-mix(in srgb, #ef4444 10%, white);
    color: #991b1b;
    border-bottom: 1px solid color-mix(in srgb, #ef4444 20%, transparent);
  }

  /* ── Body: result rows + QR side by side ─────────────────────────────── */
  .verify-body {
    display: flex;
    align-items: stretch;
    gap: 0;
    padding: 0;
  }

  /* ── Result rows ─────────────────────────────────────────────────────── */
  .verify-grid {
    flex: 1;
    display: flex;
    flex-direction: column;
    padding: 1.25rem 1.5rem;
    gap: 0.25rem;
    border-right: 1px solid #f3f4f6;
  }

  .vrow {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.45rem 0;
    border-bottom: 1px solid #f3f4f6;
    font-size: 0.875rem;
    gap: 1rem;
  }
  .vrow:last-child {
    border-bottom: none;
  }
  .vrow span {
    color: #6b7280;
    flex-shrink: 0;
  }
  .vrow strong {
    color: #111827;
    text-align: right;
    word-break: break-word;
  }

  /* ── QR panel ────────────────────────────────────────────────────────── */
  .qr-panel {
    flex-shrink: 0;
    width: 160px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.625rem;
    padding: 1.25rem 1rem;
    background: #f9fafb;
    justify-content: center;
  }

  .qr-wrap {
    width: 140px;
    height: 140px;
    background: white;
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    box-shadow: 0 1px 4px rgba(0, 0, 0, 0.06);
  }

  .qr-canvas {
    width: 140px !important;
    height: 140px !important;
    display: block;
  }

  .qr-label {
    font-size: 0.68rem;
    font-weight: 600;
    color: #6b7280;
    text-align: center;
    margin: 0;
    text-transform: uppercase;
    letter-spacing: 0.04em;
  }

  .qr-download {
    display: inline-flex;
    align-items: center;
    gap: 0.3rem;
    padding: 0.35rem 0.75rem;
    background: white;
    border: 1px solid #e5e7eb;
    border-radius: 0.4rem;
    font-size: 0.72rem;
    font-weight: 700;
    color: #374151;
    cursor: pointer;
    font-family: inherit;
    transition: all 0.15s;
  }

  .qr-download:hover:not(:disabled) {
    border-color: #10b981;
    color: #10b981;
    background: #f0fdf4;
  }

  .qr-download:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  /* ── Disclaimer ──────────────────────────────────────────────────────── */
  .verify-disclaimer {
    display: flex;
    align-items: flex-start;
    gap: 0.5rem;
    padding: 1rem 1.5rem;
    background: #fef3c7;
    font-size: 0.72rem;
    color: #92400e;
    line-height: 1.55;
    border-top: 1px solid #fde68a;
  }

  /* ── Responsive ──────────────────────────────────────────────────────── */
  @media (max-width: 520px) {
    .verify-body {
      flex-direction: column;
    }
    .verify-grid {
      border-right: none;
      border-bottom: 1px solid #f3f4f6;
    }
    .qr-panel {
      width: 100%;
      flex-direction: row;
      flex-wrap: wrap;
      justify-content: center;
      padding: 1rem;
    }

    .qr-wrap {
      width: 120px;
      height: 120px;
    }

    .qr-canvas {
      width: 120px !important;
      height: 120px !important;
    }

    .vrow {
      font-size: 0.8rem;
    }
  }

  @media (max-width: 400px) {
    .verify-header h1 {
      font-size: 1.1rem;
    }

    .verify-grid {
      padding: 1rem;
    }

    .vrow {
      flex-direction: column;
      align-items: flex-start;
      gap: 0.2rem;
    }

    .vrow strong {
      text-align: left;
      width: 100%;
    }
  }
</style>